default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: biblia_development
  # Use as suas credenciais locais aqui
  # username: postgres
  # password:

test:
  <<: *default
  database: biblia_test

production:
  # Esta configuração força o Rails a usar APENAS o DATABASE_URL
  # fornecido pelo Render, ignorando qualquer outra configuração.
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>