# config/database.yml - Versão Final e Definitiva para Rails 8 no Render

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: biblia_development
  # Use as suas credenciais locais aqui
  # username: postgres
  # password:

test:
  <<: *default
  database: biblia_test

production:
  # Esta é a base de dados principal. Ela usa a URL do Render.
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>

  # As configurações abaixo dizem ao Rails para usar a mesma base de dados
  # principal para todas as outras funcionalidades.
  solid_cache:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>
  solid_queue:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>
  solid_cable:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>