# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: biblia_development
  username: postgres
  password: 123456
  host: localhost

test:
  <<: *default
  database: biblia_test
  username: postgres
  password: "123456" 
  host: localhost

production:
  # Esta configuração usa ENV[], que não causa erro se a variável
  # não existir no ambiente de desenvolvimento, mas funciona perfeitamente
  # em produção, onde a variável DATABASE_URL é fornecida pelo Render.
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>